version: '3'
services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # do not try to map a folder up against app/node_modules inside the container
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # we ignore the ports since to run tests we are not using a server
    volumes:
      - /app/node_modules # do not try to map a folder up against app/node_modules inside the container
      - .:/app
    command: ['npm', 'run', 'test']
